# Generated by Django 5.1.4 on 2025-01-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0002_alter_programmer_options'),
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='programmers.programmer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Developer Allocation',
                'verbose_name_plural': 'Developer Allocations',
                'unique_together': {('project', 'developer')},
            },
        ),
    ]
