services:
  web:
    build: .
    command: >
      sh -c "python wait_for_db.py &&
      python manage.py makemigrations &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
