# Generated by Django 5.1.4 on 2025-01-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmer',
            options={'verbose_name': 'Programmer', 'verbose_name_plural': 'Programmers'},
        ),
    ]
